# Generated by Django 5.2.4 on 2025-07-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_userloginhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userloginhistory',
            options={'ordering': ['-login_time']},
        ),
        migrations.AddField(
            model_name='userloginhistory',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('FAILED_ATTEMPT', 'Tentative échouée')], default='LOGIN', max_length=15),
        ),
    ]
